name = "Jive"
uuid = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
keywords = ["distributed", "test"]
license = "MIT"
desc = "some useful steps in tests"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.3.13-DEV"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"

[weakdeps]
DaemonMode = "d749ddd5-2b29-4920-8305-6ff5a704e36e"

[extensions]
DaemonModeExt = "DaemonMode"

[compat]
Distributed  = "1.5, 1.6, 1.10, 1.11"
FileWatching = "1.5, 1.6, 1.10, 1.11"
Pkg          = "1.5, 1.6, 1.10, 1.11"
Printf       = "1.5, 1.6, 1.10, 1.11"
REPL         = "1.5, 1.6, 1.10, 1.11"
Test         = "1.5, 1.6, 1.10, 1.11"
Logging      = "1.5, 1.6, 1.10, 1.11"
Random       = "1.5, 1.6, 1.10, 1.11"
IOCapture    = "0.2, 1"
DaemonMode   = "0.1"
julia        = "1.0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
DaemonMode = "d749ddd5-2b29-4920-8305-6ff5a704e36e" # julia 1.6

[targets]
test = ["Test", "Logging", "Random"]
